/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GuideIdRouteImport } from './routes/guide.$id'
import { Route as PlaceIdRouteImport } from './routes/place.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIdRoute = GuideIdRouteImport.update({
  id: '/guide/$id',
  path: '/guide/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceIdRoute = PlaceIdRouteImport.update({
  id: '/place/$id',
  path: '/place/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/journal': typeof JournalRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/guide/$id': typeof GuideIdRoute
  '/place/$id': typeof PlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/journal': typeof JournalRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/guide/$id': typeof GuideIdRoute
  '/place/$id': typeof PlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/journal': typeof JournalRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/guide/$id': typeof GuideIdRoute
  '/place/$id': typeof PlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/explore'
    | '/journal'
    | '/passport'
    | '/profile'
    | '/guide/$id'
    | '/place/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/explore'
    | '/journal'
    | '/passport'
    | '/profile'
    | '/guide/$id'
    | '/place/$id'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/explore'
    | '/journal'
    | '/passport'
    | '/profile'
    | '/guide/$id'
    | '/place/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  JournalRoute: typeof JournalRoute
  PassportRoute: typeof PassportRoute
  ProfileRoute: typeof ProfileRoute
  GuideIdRoute: typeof GuideIdRoute
  PlaceIdRoute: typeof PlaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$id': {
      id: '/guide/$id'
      path: '/guide/$id'
      fullPath: '/guide/$id'
      preLoaderRoute: typeof GuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$id': {
      id: '/place/$id'
      path: '/place/$id'
      fullPath: '/place/$id'
      preLoaderRoute: typeof PlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  JournalRoute: JournalRoute,
  PassportRoute: PassportRoute,
  ProfileRoute: ProfileRoute,
  GuideIdRoute: GuideIdRoute,
  PlaceIdRoute: PlaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
